[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ausd_confidential_program = "B1eNXbLswHP3rGbAR3afynnP9yWQi5L6NEb3amGudEgj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/abriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
